import Head from "next/head";
import styles from './NavBar.module.css';

const NavBar = () => {
    return (
    <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <nav className={styles.navbar}> 
        
        <img alt="Tufts University Logo" src="/TuftsLogo.svg"/>
        
        <a href="/html/">Home</a>
        <a href="/html/">Dashboard</a>
        <a href="/html/">Devices</a>
        <a href="/html/">MapOveriew</a>
        <a href="/html/">Contact</a>

        </nav>


  
        <main className={styles.main}></main>
  
        
      </div>
      );
};

export default NavBar;



